apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if (lookup "v1" "Service" "ingress-nginx" "ingress-nginx-controller")}}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    targetPort: {{ .targetPort }}
    port: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}